#include <iostream>
#include <algorithm>
using namespace std;

class Aircraft {
    private:
        double elevatorAngle;
        double pitchInertia=5;//idk this 5 is just a random number to make the simulation work, it is not based on any real aircraft data. Pitch için atalet bu dönme direnci
        double elevatorMomentCoefficient=2;//idk this 2 is just a random number to make the simulation work, it is not based on any real aircraft data. bu da pitch için kontrol yüzeyinin moment katsayısı. Normalde işte yüzey alanı fln hesaplanıyo
        double pitch;
        double pitchRate;
    public:
    /// Update the physics of the aircraft based on the control input and time step
        double getElevatorAngle(){
            return elevatorAngle;
        }
        void update(double dt){
            double controlMoment = elevatorMomentCoefficient * elevatorAngle;// This is the moment generated by the elevator
            //add damping effect to the pitch rate like wind force or air resistance
            //Kontrol komutu uçağa açısal hız kazandırdı; uçak hedef açıya geldiğinde hâlâ yüksek açısal hıza sahipti. Damping bu açısal hareketi sönümledi
            double dampingMoment= pitchRate*-0.4;
            double netMoment = controlMoment + dampingMoment;
            double angularAcceleration = netMoment / pitchInertia;
            pitchRate = pitchRate + angularAcceleration * dt;
            pitch= pitch + pitchRate * dt;
        
        };
        double getPitch(){
            return pitch;
        }
        double getPitchRate(){
            return pitchRate;
        }
        void setPitchRate(double rate){
            pitchRate = rate;
        }
        void setElevatorAngle(double input){
            // Limit the control input to a range of -10 to 10 like real aircraft control surfaces
            elevatorAngle = min(10.0, max(-10.0, input)) ;
        }

        Aircraft(){
        elevatorAngle = 0;
        pitch = 0;
        pitchRate = 0;
        }
};
class PIDController {
    private:
        double Kp= 0.75;
        double Ki= 0.01;
        double Kd= 0.75;
        double integral;
        double previousError;
    public:
    PIDController(){
        integral = 0;
        previousError = 0;
    }   
    double compute(double ControlInput, double target, double current, double dt){
        double error= target - current;
        if (ControlInput == 10 && error > 0){
            //for integral windup.
        }
        else if (ControlInput == -10 && error < 0){
            //for integral windup.
        }
        else{
            integral += error * dt;
        }
        double derivative = (error - previousError) / dt;
        previousError = error;  
        return Kp * error + Ki * integral + Kd * derivative;
    }
    double getIntegral(){
        return integral;
    }

};
int main(){
PIDController pid;
Aircraft kerkenez;
cout << "Pitch Rate: " << kerkenez.getPitchRate() << endl;
for (int i =0; i<30; i++){
    double pidOutput = pid.compute(kerkenez.getElevatorAngle(),30, kerkenez.getPitch(), 0.1);
    kerkenez.setElevatorAngle(pidOutput);

    kerkenez.update(0.1);
    cout << "Pitch: " << kerkenez.getPitch() << endl;
    cout << "Pitch Rate: " << kerkenez.getPitchRate() << endl;
    cout << "Control Input: " << pidOutput << endl;
    cout<<"pid output: "<<pidOutput<<endl;
    cout<<"actual control input: "<<kerkenez.getElevatorAngle()<<endl;
    cout<<"integral: "<<pid.getIntegral()<<endl;
}


return 0;
}